# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               B Ark
tagline:             ''
#description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:         ''
url:                 http://NickDGreg.github.io/NickDGreg.github.io
baseurl:             ''
paginate:            5
signup_description: Do you want to work on reducing climate change? Do you want to know where you should work to maximise your impact? Do you want to see the impact of projects and companies when deciding where to contribute your hours? I'm trying to build something to do that. Subscribe and I'll update you on the progress. Maybe you can even help me build it. Have a good day :) Nick 
# About/contact
author:
  name:              Nick Gregory
  url:               
  email:             

# Custom vars
version:             1.0.0

theme: jekyll-theme-minimal