# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               B Ark
tagline:             ''
#description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:         ''
url:                 http://NickDGreg.github.io/NickDGreg.github.io
baseurl:             ''
paginate:            5
signup_description: I am answering the question of where a technologist can work to maximise their impact in climate change. If that's your ambition too, sign up for updates. Have a good day :) Nick. 
# About/contact
author:
  name:              Nick Gregory
  url:               
  email:             

# Custom vars
version:             1.0.0

theme: jekyll-theme-minimal